### ISSUE TITLE
Switch to laminas packages

### ISSUE THREAD

**Issue by xepozz** [mcustiel/PowerRoute#5]
Due to Zend was renamed to Laminas each package was changed too.

I suggest to change `zendframework/zend-diactoros` to `laminas/laminas-diactoros` to remove composer warning:

`Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead`

**Comment by alexdodonov** [comment]
@xepozz good idea but looks like this router is abandoned too
